1D Array

In [14]:
import numpy as np

# Creating a single dimensional array
arr1 = np.array([11, 22, 33, 44, 55,"Wajeeha Imtiaz"])
print(arr1)


['11' '22' '33' '44' '55' 'Wajeeha Imtiaz']


2D Arrays

In [8]:
# Creating a 2-dimensional array
array1 = np.array([[1, 2, 3], [4, 5, 6]])
print(array1, "\n")

array2 = np.array([["Jiya", "Fatima", "Saima"], ["Sarwat", "Imtiaz", "Hassan"]])
print(array2)

[[1 2 3]
 [4 5 6]] 

[['Jiya' 'Fatima' 'Saima']
 ['Sarwat' 'Imtiaz' 'Hassan']]


Arithmetic Operations On Multi dmentional Arrays

In [9]:
# Adding two 2-dimensional arrays
arr3 = np.array([[187908, 265447, 557683], [4098897, 234565, 9786]])
arr4 = np.array([[776978, 8675, 9098], [1000, 1001, 1200]])

arr5 = arr3 + arr4
print(arr5)


[[ 964886  274122  566781]
 [4099897  235566   10986]]
